version: "3"

services:
  client:
    build: ./client
    ports:
      - "3000:3000"
  server:
    build: ./server
    depends_on:
      - mysql
    ports:
      - "5555:5000"
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb+srv://root:root@cluster0.f0ojb.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
